steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--tag=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_BRANCH_NAME"
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_BRANCH_NAME"
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_BRANCH_NAME"
      - "--region=$_DEPLOY_REGION"
      - "--allow-unauthenticated"
      - "--port=80"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$_BRANCH_NAME"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: asia-southeast1
  _GCR_HOSTNAME: asia.gcr.io
  _PLATFORM: managed
  _BRANCH_NAME: master
  _SERVICE_NAME: cms-doctor-master
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
timeout: 12000s
